# Default values for mlops-factory.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: wbe7/mlops-factory
  pullPolicy: Always
  tag: "v0.1.3"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
    nginx.ingress.kubernetes.io/proxy-body-size: "10g"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
  hosts:
    - host: mlops-factory.cloudnative.space
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: mlops-factory-tls
      hosts:
        - mlops-factory.cloudnative.space

resources: {}

livenessProbe:
  httpGet:
    path: /health
    port: 8000
readinessProbe:
  httpGet:
    path: /health
    port: 8000

startupProbe:
  httpGet:
    path: /health
    port: 8000
  initialDelaySeconds: 120
  periodSeconds: 10
  failureThreshold: 10

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

# Additional volumes on the output Deployment definition.
volumes: []

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []

env:
  - name: MLFLOW_TRACKING_URI
    value: "https://mlflow.cloudnative.space"
  - name: MLFLOW_TRACKING_USERNAME
    valueFrom:
      secretKeyRef:
        name: mlflow-tracking
        key: admin-user
  - name: MLFLOW_TRACKING_PASSWORD
    valueFrom:
      secretKeyRef:
        name: mlflow-tracking
        key: admin-password
  - name: MODEL_NAME
    value: "california-housing-model"
  - name: MODEL_ALIAS
    value: "prod"

nodeSelector: {}

tolerations: []

affinity: {}
