name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Configure DVC
        env:
          S3_ENDPOINT_URL: ${{ secrets.S3_ENDPOINT_URL }}
          S3_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
          S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
        run: |
          dvc remote modify s3-origin endpointurl $S3_ENDPOINT_URL
          dvc remote modify --local s3-origin access_key_id $S3_ACCESS_KEY_ID
          dvc remote modify --local s3-origin secret_access_key $S3_SECRET_ACCESS_KEY

      - name: Pull DVC data
        run: dvc pull

      - name: Run DVC pipeline
        run: dvc repro

      - name: Commit dvc.lock
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(ci): Update dvc.lock"
          file_pattern: dvc.lock
